config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :players

  post "apis/users/sign_in", to: "application#api_login"
  root to: "players#index"
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :position

  validates :name,        presence: true
  validates :season,      numericality: {greather_than: 100, less_than: 100}
  validates :position_id, presence: true
  validates :sell, :season_one, :season_two, :season_three, :season_four,
            :season_five, :season_six, :season_seven, :season_eight,
            inclusion: [true, false]

  def age
    System::SEASON - self.season
  end

  # return how much seasons the player is on ManagerZone
  # the player starts with 16, so if he has 17, he is one season on MZ
  def mz_seasons
    age - System::JUNIOR_START_AGE
  end

  def goalkeeper?
    self.position_id == Position.first.try(:id)
  end

end

app/models/position.rb
class Position < ActiveRecord::Base
  validates :name, presence: true

  def to_s
    name
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def generate_token
    self.update_attribute :auth_token, Devise.friendly_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
  before_action :api_authentication, except: :api_login

  def api_login
    login = params['login']
    password = params['password']
    user = User.where(email: login).first
    if user && user.valid_password?(password)
      user.generate_token()
      render json: {auth_token: user.auth_token}
    else
      render json: {error: 'Login ou senha inválidos'}, status: 401
    end
  end

  def api_authentication
    auth_token = request.headers['Authorization']
    if auth_token
      user = User.where(auth_token: auth_token).first
      if user
        sign_in user, store: false
      else
        authenticate_user!
      end
    else
      authenticate_user!
    end
  end
end

app/controllers/concerns/system.rb
class System
	SEASON = 63
	JUNIOR_START_AGE = 16
	SEASONS_STR = ['season_one', 'season_two', 'season_three', 'season_four', 'season_five', 'season_six', 'season_seven', 'season_eight']
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all.order(:season, :position_id, :name)
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to players_url, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to players_url, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :season, :position_id, :sell,
        :season_one, :season_two, :season_three, :season_four, :season_five,
        :season_six, :season_seven, :season_eight)
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MzYouth</title>
  <link rel="stylesheet" media: "all" href="/bootstrap-reboot.min.css">
  <link rel="stylesheet" media: "all" href="/bootstrap-grid.min.css">
  <link rel="stylesheet" media: "all" href="/bootstrap.min.css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="root"></div>
  <script src="/bundle.js"></script>
</body>
</html>

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :season %><br>
    <%= f.number_field :season %>
  </div>
  <div class="field">
    <%= f.label :position_id %><br>
    <%= f.select :position_id, Position.all.map { |p| [p.name, p.id] } %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/_index_head.html.erb
<thead>
  <% age = System::SEASON - season %>

  <tr class="under-age">
    <th colspan="15">U<%= age %> (Season <%= season %>)</th>
  </tr>

  <tr class="head">
    <th>N</th>
    <th>Name</th>
    <th>Position</th>
    <th>Sell</th>
    <% if age >= 16 %><th>T<%= System::SEASON %></th><% end %>
    <% if age >= 17 %><th>T<%= System::SEASON - 1 %></th><% end %>
    <% if age >= 18 %><th>T<%= System::SEASON - 2 %></th><% end %>
    <% if age >= 19 %><th>T<%= System::SEASON - 3 %></th><% end %>
    <% if age >= 20 %><th>T<%= System::SEASON - 4 %></th><% end %>
    <% if age >= 21 %><th>T<%= System::SEASON - 5 %></th><% end %>
    <% if age >= 22 %><th>T<%= System::SEASON - 6 %></th><% end %>
    <% if age >= 23 %><th>T<%= System::SEASON - 7 %></th><% end %>
    <th colspan="2"></th>
  </tr>
</thead>

app/views/players/_index_player.html.erb
<% css_classes = 'player' %>
<% if player.sell %>
<%  css_classes << ' sell' %>
<% elsif player[System::SEASONS_STR[player.mz_seasons()]] %>
<%  css_classes << ' tc' %>
<% end %>

<tr class="<%= css_classes %>" id="player-<%=player.id%>">
  <td><%= number %></td>
  <td><%= player.name %></td>
  <td><%= player.position.name %></td>
  <td><%= check_box_tag 'sell', 1, player.sell, onclick: "playerAttribChange(this, '#{player.id}')" %></td>

  <% season_age = System::JUNIOR_START_AGE %>
  <% player_seasons = System::SEASONS_STR[0..player.mz_seasons()].reverse() %>
  <% player_seasons.each do |season| %>
    <% if player.age >= season_age %>
      <td><%= check_box_tag season, 1, player[season], onclick: "playerAttribChange(this, '#{player.id}')" %></td>
    <% end %>
    <% season_age += 1 %>
  <% end %>

  <td><%= link_to 'Edit', edit_player_path(player) %></td>
  <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form' %>

app/views/players/index.html.erb
<div class="centered-panel">
<p id="notice"><%= notice %></p>

<h1>Players</h1>
<h3><%= link_to 'New Player', new_player_path %></h3>

<% number = 10 %>

<% @players.map(&:season).uniq.each do |season| %>
  <% number = number + 10 - (number % 10) %>

  <table class="player-table">
    <%= render template: 'players/_index_head', locals: {season: season} %>

    <tbody>
      <% @players.where(season: season).each do |player| %>
        <% number += 1 if !player.goalkeeper? && (number % 10) == 0 %>
        <%= render template: 'players/_index_player', locals: {player: player, number: number += 1} %>
      <% end %>
    </tbody>
  </table>
  <br/>
<% end %>

app/views/players/new.html.erb
<div class="centered-panel">
<h1>New Player</h1>

<%= render 'form' %>
</div>